version: "3"
services:
  ubuntu_node:
    build: .
    image: bolt-spec
    ports:
      - "20022:22"
    container_name: ubuntu_node
  puppet_5_node:
    image:  bolt-spec
    depends_on:
      - ubuntu_node
    ports:
      - "20023:22"
  puppet_6_node:
    image:  bolt-spec
    depends_on:
      - ubuntu_node
    ports:
      - "20024:22"
  puppetserver:
    build:
      context: .
      dockerfile: Dockerfile.puppetserver
    image: puppet-server
    ports:
      - "8140:8140"
    volumes:
      - ./fixtures/modules:/etc/puppetlabs/code/modules
