version: "3"
services:
  ubuntu_node:
    build: .
    container_name: ubuntu_node
    ports:
      - "20022:22"

  puppet_6_node:
    build:
      context: .
      args:
        PUPPET_COLLECTION: puppet6
    container_name: puppet_6_node
    ports:
      - "20024:22"

  puppet_7_node:
    build:
      context: .
      args:
        PUPPET_COLLECTION: puppet7
    container_name: puppet_7_node
    ports:
      - "20025:22"

  postgres:
    image: postgres:11.11
    environment:
      POSTGRES_PASSWORD: puppetdb
      POSTGRES_USER: puppetdb
      POSTGRES_DB: puppetdb
    volumes:
      - ./fixtures/puppetdb/custom_source:/docker-entrypoint-initdb.d

  puppetdb:
    build:
      context: .
      dockerfile: Dockerfile.puppetdb
    depends_on:
      - postgres
      - puppetserver
    environment:
      USE_PUPPETSERVER: 'false'
      CERTNAME: pdb
    ports:
      - "18081:8081"

  puppetserver:
    build:
      context: .
      dockerfile: Dockerfile.puppetserver
    image: puppet-server
    ports:
      - "8140:8140"
    volumes:
      - ./fixtures/modules:/etc/puppetlabs/code/modules
