title: Bolt Hands-on Lab
google_analytics: UA-120367942-3
exclude: [vendor, Boltdir, acceptance, modules, .git, Gemfile, Gemfile.lock]

collections:
  lab:
    output: true
  examples:
    output: true

defaults:
  - scope:
      type: lab
    values:
      layout: lab
  - scope:
      type: examples
    values:
      layout: example
