name: Bolt Server

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - .github/workflows/bolt_server.yaml
      - bolt.gemspec
      - Gemfile
      - Puppetfile
      - bolt-modules/**
      - lib/bolt/**
      - lib/bolt_server/**
      - libexec/**
      - rakelib/tests.rake
      - spec/**

env:
  BOLT_WINRM_USER: roddypiper
  BOLT_WINRM_HOST: localhost
  BOLT_WINRM_PORT: 5985
  BOLT_WINRM_SSL_PORT: 5986
  BOLT_WINRM_SMB_PORT: 445

jobs:
  tests:
    name: Tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        ruby: [3.1]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Update gems
        run: bundle update
      - name: Cache modules
        id: modules
        uses: actions/cache@v1
        with:
          path: modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/Puppetfile') }}
      - name: Install modules
        if: steps.modules.outputs.cache-hit != 'true'
        run: bundle exec r10k puppetfile install
      - if: runner.os == 'Linux'
        uses: ./.github/actions/docker_setup
      - if: runner.os == 'Windows'
        uses: ./.github/actions/windows_agentless_setup
      - name: Run tests
        if: runner.os == 'Windows'
        run: bundle exec rake ci:boltserver:windows
      - name: Run tests
        if: runner.os == 'Linux'
        run: bundle exec rake ci:boltserver:linux
