name: Docker transport

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - .github/workflows/docker_transport.yaml
      - bolt.gemspec
      - Gemfile
      - Puppetfile
      - bolt-modules/**
      - lib/bolt/**
      - libexec/**
      - rakelib/tests.rake
      - spec/**

jobs:
  docker_transport:
    name: Docker Transport
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ruby: [3.1]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Update gems
        run: bundle update
      - name: Cache modules
        id: modules
        uses: actions/cache@v1
        with:
          path: modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/Puppetfile') }}
      - name: Install modules
        if: steps.modules.outputs.cache-hit != 'true'
        run: bundle exec r10k puppetfile install
      - uses: ./.github/actions/sudo_setup
      - name: Run tests
        run: bundle exec rake ci:docker_transport
