name: Linux

on:
  push:
    branches: [main]
    paths-ignore: ['**.md', '**.erb', 'schemas/*']
  pull_request:
    type: [opened, reopened, edited]
    paths-ignore: ['**.md', '**.erb', 'schemas/*']

env:
  BOLT_SUDO_USER: true

jobs:

  fast:
    name: Fast
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.5.x'
      - name: Install bundler
        run: |
          gem install bundler
          bundle config path vendor/bundle
      - name: Cache gems
        id: cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('lib/bolt/version.rb') }}-${{ hashFiles('Gemfile') }}-${{ hashFiles('bolt.gemspec') }}
      - name: Install gems
        if: steps.cache.outputs.cache-hit != 'true'
        run: bundle install --jobs 4 --retry 3
      - name: Pre-test setup
        run: |
          echo 'runner:runner' | sudo chpasswd
          sudo sh -c "echo 'Defaults authenticate' >> /etc/sudoers"
          sudo sh -c "echo 'runner  ALL=(ALL) PASSWD:ALL' >> /etc/sudoers"
          docker-compose -f spec/docker-compose.yml build --parallel ubuntu_node puppet_5_node puppet_6_node
          docker-compose -f spec/docker-compose.yml up -d ubuntu_node puppet_5_node puppet_6_node
          chmod 0600 spec/fixtures/keys/id_rsa
          bundle exec r10k puppetfile install
      - name: Run tests with minimal container infrastructure
        run: bundle exec rake ci:fast

  slow:
    name: Slow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.5.x'
      - name: Install bundler
        run: |
          gem install bundler
          bundle config path vendor/bundle
      - name: Cache gems
        id: cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('lib/bolt/version.rb') }}-${{ hashFiles('Gemfile') }}-${{ hashFiles('bolt.gemspec') }}
      - name: Install gems
        if: steps.cache.outputs.cache-hit != 'true'
        run: bundle install --jobs 4 --retry 3
      - name: Pre-test setup
        run: |
          docker-compose -f spec/docker-compose.yml build --parallel
          docker-compose -f spec/docker-compose.yml up -d
          bundle exec r10k puppetfile install
      - name: Run tests with expensive containers
        run: bundle exec rake ci:slow
