name: Local Transport

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - .github/workflows/local_transport.yaml
      - bolt.gemspec
      - Gemfile
      - Puppetfile
      - bolt-modules/**
      - lib/bolt/**
      - libexec/**
      - rakelib/tests.rake
      - spec/**

env:
  BOLT_WINRM_USER: roddypiper
  BOLT_WINRM_HOST: localhost
  BOLT_WINRM_PORT: 5985
  BOLT_WINRM_SSL_PORT: 5986
  BOLT_WINRM_SMB_PORT: 445

jobs:
  tests:
    name: Tests
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-latest]
        ruby: [3.1]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Update gems
        run: bundle update
      - name: Cache modules
        id: modules
        uses: actions/cache@v1
        with:
          path: modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/Puppetfile') }}
      - name: Install modules
        if: steps.modules.outputs.cache-hit != 'true'
        run: bundle exec r10k puppetfile install
      - if: matrix.os == 'ubuntu-24.04'
        uses: ./.github/actions/sudo_setup
      - if: matrix.os == 'windows-latest'
        uses: ./.github/actions/windows_agent_setup
      - if: matrix.os == 'ubuntu-24.04'
        name: Run tests
        run: bundle exec rake ci:local_transport:linux
      - if: matrix.os == 'windows-latest'
        name: Run tests
        run: bundle exec rake ci:local_transport:windows
