name: Modules

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - .github/workflows/modules.yaml
      - bolt.gemspec
      - Gemfile
      - Puppetfile
      - bolt-modules/**
      - bolt_spec_spec/**
      - lib/bolt/**
      - modules/**
      - rakelib/tests.rake

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.7, 3.2]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Update gems
        run: bundle update
      - name: Run module tests
        run: bundle exec rake ci:modules

  windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      matrix:
        ruby: [2.7, 3.2]
    env:
      BOLT_WINDOWS: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Update gems
        run: bundle update
      - name: Run module tests
        run: bundle exec rake ci:modules
