name: Schemas

on:
  push:
    branches: [main]
    paths:
      - 'rakelib/schemas.rake'
      - 'schemas/*.json'
      - 'lib/bolt/config/options.rb'
      - 'lib/bolt/config/transport/options.rb'
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - 'rakelib/schemas.rake'
      - 'schemas/*.json'
      - 'lib/bolt/config/options.rb'
      - 'lib/bolt/config/transport/options.rb'

jobs:

  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Update gems
        run: bundle update
      - name: Generate schemas
        run: bundle exec rake schemas:all
      - name: Compare changes
        run: |
          if git diff --quiet; then
            echo 'Did not detect changes to JSON schemas'
            exit 0
          else
            echo 'Detected changes to JSON schemas. Run schema generation task and commit changes:
            bundle exec rake schemas:all'
            exit 1
          fi
