name: SSH Transport

on:
  push:
    branches: [main]
    paths-ignore: ['**.md', '**.erb', 'schemas/*']
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths-ignore: ['**.md', '**.erb', 'schemas/*']

jobs:
  ssh_transport:
    name: SSH Transport
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.7, 3.1]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Update gems
        run: bundle update
      - name: Cache modules
        id: modules
        uses: actions/cache@v1
        with:
          path: modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/Puppetfile') }}
      - name: Install modules
        if: steps.modules.outputs.cache-hit != 'true'
        run: bundle exec r10k puppetfile install
      - uses: ./.github/actions/sudo_setup
      - name: Run tests
        run: bundle exec rake ci:ssh_transport
