name: Windows

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - .github/workflows/windows.yaml
      - bolt.gemspec
      - Gemfile
      - Puppetfile
      - bolt-modules/**
      - lib/bolt/**
      - libexec/**
      - rakelib/tests.rake
      - spec/**

env:
  BOLT_WINRM_USER: roddypiper
  BOLT_WINRM_HOST: localhost
  BOLT_WINRM_PORT: 5985
  BOLT_WINRM_SSL_PORT: 5986
  BOLT_WINRM_SMB_PORT: 445
  
jobs:
  integration:
    name: Integration
    runs-on: windows-latest
    strategy:
      matrix:
        ruby: [2.7, 3.1]
    env:
      WINDOWS_AGENTS: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Update gems
        run: bundle update
      - name: Cache modules
        id: modules
        uses: actions/cache@v1
        with:
          path: modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/Puppetfile') }}
      - name: Install modules
        if: steps.modules.outputs.cache-hit != 'true'
        run: bundle exec r10k puppetfile install
      - uses: ./.github/actions/windows_agent_setup
      - name: Run tests
        run: bundle exec rake ci:windows:integration

  agentless:
    name: Agentless
    runs-on: windows-latest
    strategy:
      matrix:
        ruby: [2.7, 3.1]
    env:
      BOLT_WINDOWS: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Update gems
        run: bundle update
      - name: Cache modules
        id: modules
        uses: actions/cache@v1
        with:
          path: modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/Puppetfile') }}
      - name: Install modules
        if: steps.modules.outputs.cache-hit != 'true'
        run: bundle exec r10k puppetfile install
      - uses: ./.github/actions/windows_agentless_setup
      - name: Run tests
        run: bundle exec rake ci:windows:agentless
